"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Union

__copyright__ = ...
__license__ = ...
class AmazonOrdersError(Exception):
    """
    Raised when a general ``amazon-orders`` error has occurred.
    """
    def __init__(self, error: Union[str, BaseException], meta: Optional[Dict[str, Any]] = ...) -> None:
        ...
    


class AmazonOrdersNotFoundError(AmazonOrdersError):
    """
    Raised when an Amazon page is not found.
    """
    ...


class AmazonOrdersAuthError(AmazonOrdersError):
    """
    Raised when an ``amazon-orders`` authentication error has occurred.
    """
    ...


class AmazonOrdersAuthRedirectError(AmazonOrdersAuthError):
    """
    Raised when an ``amazon-orders`` session that was previously authenticated redirects to login, indicating the
    likely need to reauthenticate.
    """
    ...


class AmazonOrdersEntityError(AmazonOrdersError):
    """
    Raised when an ``amazon-orders`` entity parsing error has occurred.
    """
    ...


