"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional
from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.transaction import Transaction
from amazonorders.session import AmazonSession

__copyright__ = ...
__license__ = ...
logger = ...
class AmazonTransactions:
    """
    Using an authenticated :class:`~amazonorders.session.AmazonSession`, can be used to query Amazon
    for Transaction details and history.
    """
    def __init__(self, amazon_session: AmazonSession, debug: Optional[bool] = ..., config: Optional[AmazonOrdersConfig] = ...) -> None:
        ...
    
    def get_transactions(self, days: int = ..., next_page_data: Optional[Dict[str, Any]] = ..., keep_paging: bool = ...) -> List[Transaction]:
        """
        Get Amazon Transaction history for a given number of days.

        :param days: The number of days worth of Transactions to get.
        :param next_page_data: If a call to this method previously errored out, passing the exception's
            :attr:`~amazonorders.exception.AmazonOrdersError.meta` will continue paging where it left off.
        :param keep_paging: ``False`` if only one page should be fetched.
        :return: A list of the requested Transactions.
        """
        ...
    


