"""This type stub file was generated by pyright."""

from datetime import date
from typing import TypeVar

from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.parsable import Parsable
from amazonorders.entity.seller import Seller
from bs4 import Tag

ItemEntity = TypeVar("ItemEntity", bound="Item")

class Item(Parsable):
    title: str
    link: str
    price: float | None
    seller: Seller | None
    condition: str | None
    return_elibible_date: date | None
    image_link: str | None
    quantity: int | None

    def __init__(self, parsed: Tag, config: AmazonOrdersConfig) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __lt__(self, other: ItemEntity) -> bool: ...
